package webapp.entities;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1

/**
 * BiletId generated by hbm2java
 */
public class BiletId implements java.io.Serializable {

    private int idBilet;
    private int idMiejsce;

    public BiletId() {
    }

    public BiletId(int idBilet, int idMiejsce) {
        this.idBilet = idBilet;
        this.idMiejsce = idMiejsce;
    }

    public int getIdBilet() {
        return this.idBilet;
    }

    public void setIdBilet(int idBilet) {
        this.idBilet = idBilet;
    }

    public int getIdMiejsce() {
        return this.idMiejsce;
    }

    public void setIdMiejsce(int idMiejsce) {
        this.idMiejsce = idMiejsce;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof BiletId)) {
            return false;
        }
        BiletId castOther = (BiletId) other;

        return (this.getIdBilet() == castOther.getIdBilet())
                && (this.getIdMiejsce() == castOther.getIdMiejsce());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdBilet();
        result = 37 * result + this.getIdMiejsce();
        return result;
    }

}
