package webapp.entities;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film implements java.io.Serializable {

    private Integer idFilm;
    private String tytul;
    private String rezyser;
    private String produkcja;
    private String opis;
    private String gatunek;
    private String cena;
    private String WWiek;
    private Float czasTrwania;
    private Set<Seans> seanses = new HashSet<Seans>(0);

    public Film() {
    }

    public Film(String tytul, String rezyser, String produkcja, String opis, String gatunek, String cena, String WWiek, Float czasTrwania, Set<Seans> seanses) {
        this.tytul = tytul;
        this.rezyser = rezyser;
        this.produkcja = produkcja;
        this.opis = opis;
        this.gatunek = gatunek;
        this.cena = cena;
        this.WWiek = WWiek;
        this.czasTrwania = czasTrwania;
        this.seanses = seanses;
    }

    public Integer getIdFilm() {
        return this.idFilm;
    }

    public void setIdFilm(Integer idFilm) {
        this.idFilm = idFilm;
    }

    public String getTytul() {
        return this.tytul;
    }

    public void setTytul(String tytul) {
        this.tytul = tytul;
    }

    public String getRezyser() {
        return this.rezyser;
    }

    public void setRezyser(String rezyser) {
        this.rezyser = rezyser;
    }

    public String getProdukcja() {
        return this.produkcja;
    }

    public void setProdukcja(String produkcja) {
        this.produkcja = produkcja;
    }

    public String getOpis() {
        return this.opis;
    }

    public void setOpis(String opis) {
        this.opis = opis;
    }

    public String getGatunek() {
        return this.gatunek;
    }

    public void setGatunek(String gatunek) {
        this.gatunek = gatunek;
    }

    public String getCena() {
        return this.cena;
    }

    public void setCena(String cena) {
        this.cena = cena;
    }

    public String getWWiek() {
        return this.WWiek;
    }

    public void setWWiek(String WWiek) {
        this.WWiek = WWiek;
    }

    public Float getCzasTrwania() {
        return this.czasTrwania;
    }

    public void setCzasTrwania(Float czasTrwania) {
        this.czasTrwania = czasTrwania;
    }

    public Set<Seans> getSeanses() {
        return this.seanses;
    }

    public void setSeanses(Set<Seans> seanses) {
        this.seanses = seanses;
    }

}
