package webapp.entities;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Klient generated by hbm2java
 */
public class Klient implements java.io.Serializable {

    private Integer idKlient;
    private String imie;
    private String nazwisko;
    private String mail;
    private String telefon;
    private String klientcol;
    private Set<Rezerwacja> rezerwacjas = new HashSet<Rezerwacja>(0);

    public Klient() {
    }

    public Klient(String imie, String nazwisko, String mail, String telefon, String klientcol, Set<Rezerwacja> rezerwacjas) {
        this.imie = imie;
        this.nazwisko = nazwisko;
        this.mail = mail;
        this.telefon = telefon;
        this.klientcol = klientcol;
        this.rezerwacjas = rezerwacjas;
    }

    public Integer getIdKlient() {
        return this.idKlient;
    }

    public void setIdKlient(Integer idKlient) {
        this.idKlient = idKlient;
    }

    public String getImie() {
        return this.imie;
    }

    public void setImie(String imie) {
        this.imie = imie;
    }

    public String getNazwisko() {
        return this.nazwisko;
    }

    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getTelefon() {
        return this.telefon;
    }

    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

    public String getKlientcol() {
        return this.klientcol;
    }

    public void setKlientcol(String klientcol) {
        this.klientcol = klientcol;
    }

    public Set<Rezerwacja> getRezerwacjas() {
        return this.rezerwacjas;
    }

    public void setRezerwacjas(Set<Rezerwacja> rezerwacjas) {
        this.rezerwacjas = rezerwacjas;
    }

}
