package webapp.entities;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Miejsce generated by hbm2java
 */
public class Miejsce implements java.io.Serializable {

    private Integer idMiejsce;
    private Sala sala;
    private Integer sektor;
    private Integer rzad;
    private Set<Bilet> bilets = new HashSet<Bilet>(0);

    public Miejsce() {
    }

    public Miejsce(Sala sala) {
        this.sala = sala;
    }

    public Miejsce(Sala sala, Integer sektor, Integer rzad, Set<Bilet> bilets) {
        this.sala = sala;
        this.sektor = sektor;
        this.rzad = rzad;
        this.bilets = bilets;
    }

    public Integer getIdMiejsce() {
        return this.idMiejsce;
    }

    public void setIdMiejsce(Integer idMiejsce) {
        this.idMiejsce = idMiejsce;
    }

    public Sala getSala() {
        return this.sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }

    public Integer getSektor() {
        return this.sektor;
    }

    public void setSektor(Integer sektor) {
        this.sektor = sektor;
    }

    public Integer getRzad() {
        return this.rzad;
    }

    public void setRzad(Integer rzad) {
        this.rzad = rzad;
    }

    public Set<Bilet> getBilets() {
        return this.bilets;
    }

    public void setBilets(Set<Bilet> bilets) {
        this.bilets = bilets;
    }

}
