package webapp.entities;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala implements java.io.Serializable {

    private Integer idSala;
    private Integer iloscMiejsc;
    private Set<Miejsce> miejsces = new HashSet<Miejsce>(0);
    private Set<Seans> seanses = new HashSet<Seans>(0);

    public Sala() {
    }

    public Sala(Integer iloscMiejsc, Set<Miejsce> miejsces, Set<Seans> seanses) {
        this.iloscMiejsc = iloscMiejsc;
        this.miejsces = miejsces;
        this.seanses = seanses;
    }

    public Integer getIdSala() {
        return this.idSala;
    }

    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }

    public Integer getIloscMiejsc() {
        return this.iloscMiejsc;
    }

    public void setIloscMiejsc(Integer iloscMiejsc) {
        this.iloscMiejsc = iloscMiejsc;
    }

    public Set<Miejsce> getMiejsces() {
        return this.miejsces;
    }

    public void setMiejsces(Set<Miejsce> miejsces) {
        this.miejsces = miejsces;
    }

    public Set<Seans> getSeanses() {
        return this.seanses;
    }

    public void setSeanses(Set<Seans> seanses) {
        this.seanses = seanses;
    }

}
