package webapp.entities;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Seans generated by hbm2java
 */
public class Seans implements java.io.Serializable {

    private Integer idSeans;
    private Film film;
    private Sala sala;
    private Date data;
    private Date godzina;
    private Set<Bilet> bilets = new HashSet<Bilet>(0);

    public Seans() {
    }

    public Seans(Film film, Sala sala) {
        this.film = film;
        this.sala = sala;
    }

    public Seans(Film film, Sala sala, Date data, Date godzina, Set<Bilet> bilets) {
        this.film = film;
        this.sala = sala;
        this.data = data;
        this.godzina = godzina;
        this.bilets = bilets;
    }

    public Integer getIdSeans() {
        return this.idSeans;
    }

    public void setIdSeans(Integer idSeans) {
        this.idSeans = idSeans;
    }

    public Film getFilm() {
        return this.film;
    }

    public void setFilm(Film film) {
        this.film = film;
    }

    public Sala getSala() {
        return this.sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }

    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public Date getGodzina() {
        return this.godzina;
    }

    public void setGodzina(Date godzina) {
        this.godzina = godzina;
    }

    public Set<Bilet> getBilets() {
        return this.bilets;
    }

    public void setBilets(Set<Bilet> bilets) {
        this.bilets = bilets;
    }

}
