package kino;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1



/**
 * Bilet generated by hbm2java
 */
public class Bilet  implements java.io.Serializable {


     private BiletId id;
     private Miejsce miejsce;
     private Rezerwacja rezerwacja;
     private Seans seans;

    public Bilet() {
    }

    public Bilet(BiletId id, Miejsce miejsce, Rezerwacja rezerwacja, Seans seans) {
       this.id = id;
       this.miejsce = miejsce;
       this.rezerwacja = rezerwacja;
       this.seans = seans;
    }
   
    public BiletId getId() {
        return this.id;
    }
    
    public void setId(BiletId id) {
        this.id = id;
    }
    public Miejsce getMiejsce() {
        return this.miejsce;
    }
    
    public void setMiejsce(Miejsce miejsce) {
        this.miejsce = miejsce;
    }
    public Rezerwacja getRezerwacja() {
        return this.rezerwacja;
    }
    
    public void setRezerwacja(Rezerwacja rezerwacja) {
        this.rezerwacja = rezerwacja;
    }
    public Seans getSeans() {
        return this.seans;
    }
    
    public void setSeans(Seans seans) {
        this.seans = seans;
    }




}


