package kino;
// Generated 2014-11-18 18:45:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rezerwacja generated by hbm2java
 */
public class Rezerwacja  implements java.io.Serializable {


     private Integer idRezerwacja;
     private Klient klient;
     private Boolean potwierdzona;
     private Set<Bilet> bilets = new HashSet<Bilet>(0);

    public Rezerwacja() {
    }

	
    public Rezerwacja(Klient klient) {
        this.klient = klient;
    }
    public Rezerwacja(Klient klient, Boolean potwierdzona, Set<Bilet> bilets) {
       this.klient = klient;
       this.potwierdzona = potwierdzona;
       this.bilets = bilets;
    }
   
    public Integer getIdRezerwacja() {
        return this.idRezerwacja;
    }
    
    public void setIdRezerwacja(Integer idRezerwacja) {
        this.idRezerwacja = idRezerwacja;
    }
    public Klient getKlient() {
        return this.klient;
    }
    
    public void setKlient(Klient klient) {
        this.klient = klient;
    }
    public Boolean getPotwierdzona() {
        return this.potwierdzona;
    }
    
    public void setPotwierdzona(Boolean potwierdzona) {
        this.potwierdzona = potwierdzona;
    }
    public Set<Bilet> getBilets() {
        return this.bilets;
    }
    
    public void setBilets(Set<Bilet> bilets) {
        this.bilets = bilets;
    }




}


